### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by xiaomengxinyo** [Palatis/XWeChatShortcut#1]
hey,bro.I think there may be something wrong with the module APK you released. It can not be installed. The mobile phone is Redmi 5 Plus, Android8.1, as shown in the figure . 
![1585993414856](https://user-images.githubusercontent.com/48215946/78423921-5ae2a500-769c-11ea-9c27-343d157e7acb.jpg)

**Comment by zhangyu4645** [comment]
Me too from Nokia 7 Plus with stock Android 10.

**Comment by xiaomengxinyo** [comment]
> 诺基亚7 Plus的Android 10也是如此。

Maybe there's something wrong with the APK file.

**Comment by Palatis** [comment]
I have no idea, you have to provide PackageManager logs for further diagnostics.
I can install with no problem.

**Comment by xiaomengxinyo** [comment]
> I have no idea, you have to provide PackageManager logs for further diagnostics.
> I can install with no problem.

@Palatis Now my operating system is Pixe Experience Plu Android 10 of Redmi 5Plus  . It's the same problem, but now there's a reason and I've taken a screenshot. 
![Screenshot_20200416-222746_Android_System](https://user-images.githubusercontent.com/48215946/79468807-faefe500-8031-11ea-9461-9bc68bb389a3.png)

**Comment by Palatis** [comment]
I didn't remember that I enabled testOnly apk, but I updated a new APK and verified that it's not testOnly.

Please try again and see if it works.

**Comment by xiaomengxinyo** [comment]
> 我不记得我启用了testOnly apk，但是我更新了一个新的APK并确认它不是testOnly。
> 
> 请重试，看看是否可行。

@Palatis It's all right now, thank you!
